# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_product_list',
            },
        ),
    ]
